name: expensemanagementapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2

  # Networking, Utilities
  http: ^1.2.2
  intl: ^0.20.2
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  file_picker: ^8.0.3
  path: ^1.9.0
  image_picker: ^1.1.2
  image: ^4.2.0
  permission_handler: ^11.3.1

  # Animations
  lottie: ^3.1.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # 🔹 Add all your asset paths here
  assets:
    - android/assets/logo.png
    - android/assets/1.png
    - android/assets/2.png
    - android/assets/3.png
    - android/assets/4.png
    - android/assets/Meeting Analytics.json

# Launcher icons configuration
flutter_launcher_icons:
  image_path: android/assets/logo.png
  android: true
  ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: android/assets/logo.png
    background_color: "#FFFFFF"
    theme_color: "#5B5BD6"
  macos:
    generate: true
    image_path: android/assets/logo.png
