"""REVOME new column to users

Revision ID: 070c46964895
Revises: 
Create Date: 2025-09-05 17:34:12.813423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '070c46964895'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_gender'), table_name='users')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='0 = Male, 1 = Female'))
    op.create_index(op.f('ix_users_gender'), 'users', ['gender'], unique=False)
    # ### end Alembic commands ###
