"""wending model

Revision ID: 3fa8c5baaafa
Revises: b7fa4abd0bbe
Create Date: 2025-09-10 14:46:32.733246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa8c5baaafa'
down_revision: Union[str, Sequence[str], None] = 'b7fa4abd0bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weddings', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'weddings', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weddings', type_='foreignkey')
    op.drop_column('weddings', 'owner_id')
    # ### end Alembic commands ###
