"""Add Gender column to users

Revision ID: b7fa4abd0bbe
Revises: 070c46964895
Create Date: 2025-09-05 17:34:57.541304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7fa4abd0bbe'
down_revision: Union[str, Sequence[str], None] = '070c46964895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.Integer(), nullable=False, comment='0 = Male, 1 = Female'))
    op.create_index(op.f('ix_users_gender'), 'users', ['gender'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_gender'), table_name='users')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
