// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjTJ3Dwi4iFEA70sfVX9gH3CCPzytgbrA',
    appId: '1:304723757911:web:acd2e3545fb3a98cfccc12',
    messagingSenderId: '304723757911',
    projectId: 'ai-powered-notes-scanner',
    authDomain: 'ai-powered-notes-scanner.firebaseapp.com',
    databaseURL: 'https://ai-powered-notes-scanner-default-rtdb.firebaseio.com',
    storageBucket: 'ai-powered-notes-scanner.firebasestorage.app',
    measurementId: 'G-XY30BL94NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaJ9nP_Rqfmee91y_gYkq8PBpdEuJq_sQ',
    appId: '1:304723757911:android:4fc14c16a5a12cbdfccc12',
    messagingSenderId: '304723757911',
    projectId: 'ai-powered-notes-scanner',
    databaseURL: 'https://ai-powered-notes-scanner-default-rtdb.firebaseio.com',
    storageBucket: 'ai-powered-notes-scanner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV_DRm2hMF0fhgjUfljcEeKIuWw2UedFU',
    appId: '1:304723757911:ios:ed13cf520f53bfe0fccc12',
    messagingSenderId: '304723757911',
    projectId: 'ai-powered-notes-scanner',
    databaseURL: 'https://ai-powered-notes-scanner-default-rtdb.firebaseio.com',
    storageBucket: 'ai-powered-notes-scanner.firebasestorage.app',
    iosBundleId: 'com.example.expensemanagementapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV_DRm2hMF0fhgjUfljcEeKIuWw2UedFU',
    appId: '1:304723757911:ios:ed13cf520f53bfe0fccc12',
    messagingSenderId: '304723757911',
    projectId: 'ai-powered-notes-scanner',
    databaseURL: 'https://ai-powered-notes-scanner-default-rtdb.firebaseio.com',
    storageBucket: 'ai-powered-notes-scanner.firebasestorage.app',
    iosBundleId: 'com.example.expensemanagementapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjTJ3Dwi4iFEA70sfVX9gH3CCPzytgbrA',
    appId: '1:304723757911:web:af9b5617567da721fccc12',
    messagingSenderId: '304723757911',
    projectId: 'ai-powered-notes-scanner',
    authDomain: 'ai-powered-notes-scanner.firebaseapp.com',
    databaseURL: 'https://ai-powered-notes-scanner-default-rtdb.firebaseio.com',
    storageBucket: 'ai-powered-notes-scanner.firebasestorage.app',
    measurementId: 'G-28DH1PCCZ3',
  );

}